# Common nickname → formal name mappings for NPPES matching.
# Keys are lowercase nicknames, values are lists of formal names (formal first).

NICKNAME_MAP = {
    'becki':   ['rebecca', 'becki'],
    'beckie':  ['rebecca', 'beckie'],
    'becky':   ['rebecca', 'becky'],
    'bert':    ['albert', 'robert', 'herbert', 'bert'],
    'bill':    ['william', 'bill'],
    'billy':   ['william', 'billy'],
    'bob':     ['robert', 'bob'],
    'bobby':   ['robert', 'bobby'],
    'brad':    ['bradley', 'bradford', 'brad'],
    'cathy':   ['catherine', 'kathleen', 'cathy'],
    'charlie': ['charles', 'charlie'],
    'chuck':   ['charles', 'chuck'],
    'chris':   ['christopher', 'christian', 'christine', 'christina', 'chris'],
    'dan':     ['daniel', 'dan'],
    'danny':   ['daniel', 'danny'],
    'dave':    ['david', 'dave'],
    'davy':    ['david', 'davy'],
    'debbie':  ['deborah', 'debbie'],
    'deb':     ['deborah', 'deb'],
    'dick':    ['richard', 'dick'],
    'don':     ['donald', 'don'],
    'donnie':  ['donald', 'donnie'],
    'drew':    ['andrew', 'drew'],
    'ed':      ['edward', 'edmund', 'ed'],
    'eddie':   ['edward', 'eddie'],
    'frank':   ['francis', 'franklin', 'frank'],
    'fred':    ['frederick', 'fred'],
    'freddie': ['frederick', 'freddie'],
    'gene':    ['eugene', 'gene'],
    'gerry':   ['gerald', 'gerard', 'gerry'],
    'jerry':   ['gerald', 'jerome', 'jerry'],
    'hank':    ['henry', 'hank'],
    'harry':   ['harold', 'henry', 'harry'],
    'jack':    ['john', 'jackson', 'jack'],
    'jake':    ['jacob', 'jake'],
    'jamie':   ['james', 'jamie'],
    'jeff':    ['jeffrey', 'jeff'],
    'jim':     ['james', 'jim'],
    'jimmy':   ['james', 'jimmy'],
    'johnny':  ['john', 'jonathan', 'johnny'],
    'kate':    ['katherine', 'catherine', 'kate'],
    'katie':   ['katherine', 'katelyn', 'katie'],
    'kathy':   ['kathleen', 'katherine', 'kathy'],
    'ken':     ['kenneth', 'ken'],
    'kenny':   ['kenneth', 'kenny'],
    'kim':     ['kimberly', 'kim'],
    'larry':   ['lawrence', 'larry'],
    'liz':     ['elizabeth', 'liz'],
    'lizzie':  ['elizabeth', 'lizzie'],
    'lisa':    ['elizabeth', 'lisa'],
    'lou':     ['louis', 'louise', 'lou'],
    'maggie':  ['margaret', 'maggie'],
    'matt':    ['matthew', 'matt'],
    'meg':     ['margaret', 'megan', 'meg'],
    'mike':    ['michael', 'mike'],
    'mick':    ['michael', 'mick'],
    'mickey':  ['michael', 'mickey'],
    'nan':     ['nancy', 'nan'],
    'nick':    ['nicholas', 'nick'],
    'nicky':   ['nicholas', 'nicky'],
    'pat':     ['patricia', 'patrick', 'pat'],
    'patty':   ['patricia', 'patty'],
    'peg':     ['margaret', 'peggy', 'peg'],
    'peggy':   ['margaret', 'peggy'],
    'pete':    ['peter', 'pete'],
    'rich':    ['richard', 'rich'],
    'richie':  ['richard', 'richie'],
    'rick':    ['richard', 'rick'],
    'ricky':   ['richard', 'ricky'],
    'rob':     ['robert', 'rob'],
    'robby':   ['robert', 'robby'],
    'ron':     ['ronald', 'ron'],
    'ronnie':  ['ronald', 'ronnie'],
    'sam':     ['samuel', 'samantha', 'sam'],
    'sandy':   ['sandra', 'sandy'],
    'steve':   ['steven', 'stephen', 'steve'],
    'sue':     ['susan', 'sue'],
    'susie':   ['susan', 'susie'],
    'ted':     ['theodore', 'edward', 'ted'],
    'tim':     ['timothy', 'tim'],
    'timmy':   ['timothy', 'timmy'],
    'tom':     ['thomas', 'tom'],
    'tommy':   ['thomas', 'tommy'],
    'tony':    ['anthony', 'tony'],
    'val':     ['valerie', 'val'],
    'vince':   ['vincent', 'vince'],
    'vic':     ['victor', 'vic'],
    'walt':    ['walter', 'walt'],
    'wendy':   ['gwendolyn', 'wendy'],
    'will':    ['william', 'will'],
    'willie':  ['william', 'willie'],
    'beth':    ['elizabeth', 'beth'],
    'betty':   ['elizabeth', 'betty'],
    'al':      ['albert', 'alfred', 'alan', 'al'],
    'andy':    ['andrew', 'andy'],
}


def expand_first_name(first_name):
    """
    Return a list of names to search for a given first name.
    If it's a known nickname, the formal name(s) come first.
    Always includes the original name.
    e.g. 'Becki' → ['rebecca', 'becki']
    """
    if not first_name:
        return [first_name]
    key = first_name.strip().lower()
    expansions = NICKNAME_MAP.get(key)
    if not expansions:
        return [first_name.lower()]
    return list(dict.fromkeys(expansions))  # dedupe, preserve order
